DEFINE VARIABLE array AS INTEGER EXTENT 5    NO-UNDO.
DEFINE VARIABLE i AS INT64       NO-UNDO.

DO i = 1 TO 5:
    UPDATE array[i]. 
END.

MESSAGE array[1]
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
