DEFINE VARIABLE vetor AS INTEGER EXTENT 10     NO-UNDO.
DEFINE VARIABLE i AS INT64       NO-UNDO.

DO i = 1 TO 10:
    UPDATE vetor[i].
END.

DO i = 10 TO 1:
    MESSAGE vetor[i]
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
END.
