DEFINE VARIABLE numero1 AS INT64       NO-UNDO.
DEFINE VARIABLE numero2 AS INT64       NO-UNDO.
DEFINE VARIABLE soma AS INT64       NO-UNDO.

PROCEDURE recebeinfo:
    DEFINE INPUT PARAMETER n1 AS INT64 NO-UNDO.
    DEFINE INPUT PARAMETER n2 AS INT64 NO-UNDO.
    DEFINE OUTPUT PARAMETER resultado AS INT64 NO-UNDO.
    
    resultado = n1 + n2. 
    
END PROCEDURE.

UPDATE numero1
       numero2. 
       
RUN recebeinfo(INPUT numero1, INPUT numero2, OUTPUT soma).

MESSAGE soma
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
