DEFINE VARIABLE i-numero AS INT64       NO-UNDO.

UPDATE i-numero.

IF i-numero >= 0 THEN
DO:
    MESSAGE 'POSITIVO'
    VIEW-AS ALERT-BOX INFORMATION.
END.
ELSE
    MESSAGE 'NEGATIVO'
    VIEW-AS ALERT-BOX INFORMATION.
    
